name: payment_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  uuid: ^4.5.1
  crypto: ^3.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  lottie: ^2.6.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.1
  shared_preferences: ^2.5.3
  provider: ^6.1.1
  url_launcher: ^6.2.4
  permission_handler: ^11.3.0
  camera: ^0.10.5+9
  intl: ^0.18.1
  shimmer: ^3.0.0
  speech_to_text: ^7.0.0
  flutter_native_splash: ^2.4.4
  emailjs: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/movie/

flutter_native_splash:
  color: "#000000" # Background color of the splash screen
  image: assets/images/splash_logo.png # Path to your splash screen logo
  android: true
  ios: true
  web: false
  android_gravity: center # Center the logo on Android
  ios_content_mode: center # Center the logo on iOS
  fullscreen: true # Make the splash screen fullscreen